# Generated by Django 4.1.7 on 2023-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='Sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
