# Generated by Django 4.1.7 on 2023-05-16 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_school_id_alter_school_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Sname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
